#+AUTHOR: Gabriel Bronzatti Moro and Lucas M. Schnorr
#+TITLE: What is the libnina?
#+LATEX_HEADER: \usepackage[margin=2cm,a4paper]{geometry}
#+STARTUP: overview indent
#+TAGS: Gabriel(G) Lucas(L) noexport(n) deprecated(d)
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+SEQ_TODO: TODO(t!) STARTED(s!) WAITING(w!) | DONE(d!) CANCELLED(c!) DEFERRED(f!)
#+mode: org
#+coding: utf-8

Libnina is a library used to reduce the energy consumption of OpenMP
parallel applications. The libnina methodology uses two steps, the
first one is necessary to generate a configuration file that will
describe the target application's behavior. In the second step, the
target application will be executed using pomp2 library with
libnina. The library uses the configuration file to reduce the energy
consumption using cpufreq calls to change the CPU frequency according
to the provided configuration file.

* Requirements

Libnina requires the =acpi-cpufreq= driver (instead of the =intel_pstate=)
because it dynamically changes the CPU frequency during runtime. The
governor must be the =userspace= that let's application-level calls
(with the appropriate permissions) to set the CPU frequency.  If you
are using Grub, you can disable =intel_pstate= by adding the following
line in the =/etc/default/grub= file.

#+BEGIN_EXAMPLE
GRUB_CMDLINE_LINUX_DEFAULT="intel_pstate=disable"
#+END_EXAMPLE

And then update =grub.cfg= by issuing the following command:

#+BEGIN_EXAMPLE
grub-mkconfig -o /boot/grub/grub.cfg
#+END_EXAMPLE

- [[https://unix.stackexchange.com/questions/121410/setting-cpu-governor-to-on-demand-or-conservative][Check here for further details about disabling =intel_pstate=]]. You
  can use the follow command line:

#+begin_src sh :results output :exports both
sudo cpupower frequency-info --governors
#+end_src

#+RESULTS:
: analyzing CPU 0:
: conservative ondemand userspace powersave performance

- In this case, it is possible to use this library, because the
  userspace governor exists.

- It's necessary the libpapi, libconfig, and libcpufreq
  installation. The follow command line may be used:

#+begin_src sh :results output :exports both
sudo apt install libpapi-dev -y
sudo apt install libconfig-dev -y
sudo apt install libcpufreq-dev -y
#+end_src
