library(readr);
library(tidyr);
library(dplyr);
library(magrittr);
library(stringr);

#read csv generated by otf22csv 
df_ipc <- read_csv("../expData/cpu/traces.csv")
df_memory <- read_csv("../expData/mem/traces.csv")

#adding header in each data frame
names(df_ipc) <- c("v1","v2","v3","v4","region","ins","cyc")
names(df_memory) <- c("v1","v2","v3","v4","region","tca","tcm")

#removing the unnecessary columns
df_ipc <- df_ipc %>% select(region, ins, cyc) %>% as.data.frame();
df_memory <- df_memory %>% select(region, tca, tcm) %>% as.data.frame();

#only parallel regions
df_ipc <- df_ipc %>% filter(grepl("parallel", region));
df_memory <- df_memory %>% filter(grepl("parallel", region));

#getting the metrics 
df_ipc$ipc <- df_ipc$ins / df_ipc$cyc;
df_memory$misses <- df_memory$tcm / df_memory$tca;

#getting the regions' column
dfT <- df_ipc %>% select(region) %>% as.data.frame();

#identify the memory bound regions
count <- 1
max <- nrow(df_ipc)

while(count < max){
    dfT$maxFreq[count] <- (df_ipc$ipc[count] < 0.40 && df_memory$misses[count]>0.20)
	count <- count + 1
}

#split to find region, line and file in the same column
dftmp1 <- str_split_fixed(dfT$region, ':', 2) %>% as.data.frame();
dftmp2 <- str_split_fixed(dfT$region, '\\@', 2) %>% as.data.frame();
dftmp3 <- str_split_fixed(dftmp2$V2, ':', 2) %>% as.data.frame();

dfT$lines <- dftmp1$V2
dfT$file <- dftmp3$V1
dfT$region <- dftmp2$V1

#sorting according libnina's configuration
dfT <- dfT %>% select(lines,maxFreq,region,file) %>% as.data.frame();

write.csv(dfT, file = "../expData/configurationFile.csv")
